# Generated by Django 5.1.2 on 2024-10-22 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=80)),
                ('summary', models.TextField(max_length=2000)),
                ('category', models.CharField(max_length=80)),
                ('author_id', models.IntegerField(default=0)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('missing', 'Missing')], default='available', max_length=10)),
            ],
            options={
                'db_table': 'library_books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booksmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
