# Generated by Django 5.1.2 on 2024-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowedbook_delete_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='duration_days',
            field=models.IntegerField(default=14),
        ),
    ]
