# Generated by Django 5.1.2 on 2024-10-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowedbook_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rent', 'Rent'), ('missing', 'Missing')], default='available', max_length=10),
        ),
    ]
