# Generated by Django 5.1.3 on 2024-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_author_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
